In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report,r2_score
from sklearn.preprocessing import MinMaxScaler

In [2]:
""" Field Name	Order	Type (Format)	Description
Date	1	date (%Y-%m-%d)	Match Date (dd/mm/yy)
HomeTeam	2	string (default)	Home Team
AwayTeam	3	string (default)	Away Team
FTHG	4	integer (default)	Full Time Home Team Goals
FTAG	5	integer (default)	Full Time Away Team Goals
FTR	6	string (default)	Full Time Result (H=Home Win, D=Draw, A=Away Win)
HTHG	7	integer (default)	Half Time Home Team Goals
HTAG	8	integer (default)	Half Time Away Team Goals
HTR	9	string (default)	Half Time Result (H=Home Win, D=Draw, A=Away Win)
HS	10	integer (default)	Home Team Shots
AS	11	integer (default)	Away Team Shots
HST	12	integer (default)	Home Team Shots on Target
AST	13	integer (default)	Away Team Shots on Target
HF	14	integer (default)	Home Team Fouls Committed
AF	15	integer (default)	Away Team Fouls Committed
HC	16	integer (default)	Home Team Corners
AC	17	integer (default)	Away Team Corners
HY	18	integer (default)	Home Team Yellow Cards
AY	19	integer (default)	Away Team Yellow Cards
HR	20	integer (default)	Home Team Red Cards
AR	21	integer (default)	Away Team Red Cards """


squadre =  {
                'Genoa' : 0,
                'Udinese' : 1,
                'Napoli'  : 2,
                'Empoli'  : 3,
                'Milan'   : 4,
                'Atalanta': 5,
                'Chievo'  : 6,
                'Juventus': 7,
                'Lazio'   : 8,
                'Spal'    : 9,
                'Parma'   : 10,
                'Cagliari': 11,
                'Sassuolo': 12,
                'Torino'  : 13,
                'Inter'   : 14,
                'Fiorentina': 15,
                'Bologna'   : 16,
                'Roma'      : 17,
                'Sampdoria' : 18,
                'Frosinone' : 19
            }

In [4]:
df = pd.read_csv("season-1819_csv.csv")

In [9]:
print(df.shape)
df.drop(['Date'], axis='columns', inplace=True) #Tolgo la colonna Date
print(df.shape)

(259, 20)

KeyError: "labels ['Date'] not contained in axis"

In [10]:
df.drop(['FTR'], axis='columns', inplace=True) #Tolgo la colonna FTR
df.drop(['HTR'], axis='columns', inplace=True) #Tolgo la colonna HTR

In [13]:
df.shape
df.head()

,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,6,7,2,3,1,1,7,23,2,11,7,9,0,8,2,0,0,0
1,8,2,1,2,1,1,9,11,5,6,8,5,4,7,0,0,0,0
2,16,9,0,1,0,0,8,10,3,5,16,11,7,0,4,2,1,0
3,3,11,2,0,1,0,9,12,4,5,19,19,6,6,3,3,0,0
4,10,1,2,2,1,0,9,16,6,6,10,13,4,5,2,2,0,0

In [8]:
df['HomeTeam'] = df['HomeTeam'].map(squadre)
df['AwayTeam'] = df['AwayTeam'].map(squadre)

In [7]:
scaler = MinMaxScaler(feature_range=(0, 1), copy=True)

In [14]:
array_scaled = scaler.fit_transform(df)

In [15]:
print(array_scaled)

[[0.31578947 0.36842105 0.33333333 ... 0.         0.         0.        ]
 [0.42105263 0.10526316 0.16666667 ... 0.         0.         0.        ]
 [0.84210526 0.47368421 0.         ... 0.28571429 0.5        0.        ]
 ...
 [0.47368421 0.94736842 0.16666667 ... 0.42857143 0.5        0.        ]
 [0.68421053 0.31578947 0.5        ... 0.57142857 0.         0.        ]
 [0.05263158 0.84210526 0.33333333 ... 0.42857143 0.         0.        ]]

In [16]:
df_scaled = pd.DataFrame(array_scaled)

In [20]:

df_scaled.columns = df.columns

In [21]:
df_scaled.head()

,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,0.315789,0.368421,0.333333,0.500000,0.25,0.333333,0.250000,1.000000,0.133333,0.846154,0.15,0.217391,0.00,0.615385,0.333333,0.000000,0.0,0.0
1,0.421053,0.105263,0.166667,0.333333,0.25,0.333333,0.333333,0.428571,0.333333,0.461538,0.20,0.043478,0.20,0.538462,0.000000,0.000000,0.0,0.0
2,0.842105,0.473684,0.000000,0.166667,0.00,0.000000,0.291667,0.380952,0.200000,0.384615,0.60,0.304348,0.35,0.000000,0.666667,0.285714,0.5,0.0
3,0.157895,0.578947,0.333333,0.000000,0.25,0.000000,0.333333,0.476190,0.266667,0.384615,0.75,0.652174,0.30,0.461538,0.500000,0.428571,0.0,0.0
4,0.526316,0.052632,0.333333,0.333333,0.25,0.000000,0.333333,0.666667,0.400000,0.461538,0.30,0.391304,0.20,0.384615,0.333333,0.285714,0.0,0.0

In [146]:
print(df_scaled.iloc[:,:2])
print(df_scaled.iloc[:,2:18])
print(type(df.iloc[:,2:6]))

     HomeTeam  AwayTeam
0    0.315789  0.368421
1    0.421053  0.105263
2    0.842105  0.473684
3    0.157895  0.578947
4    0.526316  0.052632
5    0.631579  0.736842
6    0.684211  0.894737
7    0.263158  1.000000
8    0.368421  0.421053
9    0.105263  0.210526
10   0.578947  0.631579
11   0.789474  0.315789
12   1.000000  0.842105
13   0.000000  0.157895
14   0.736842  0.684211
15   0.473684  0.526316
16   0.052632  0.947368
17   0.894737  0.263158
18   0.210526  0.894737
19   0.842105  0.736842
20   0.526316  0.368421
21   0.263158  0.578947
22   0.315789  0.157895
23   0.789474  0.052632
24   0.421053  1.000000
25   0.947368  0.105263
26   0.631579  0.000000
27   0.684211  0.473684
28   1.000000  0.947368
29   0.736842  0.526316
..        ...       ...
229  0.684211  0.052632
230  0.368421  1.000000
231  0.263158  0.210526
232  0.578947  0.526316
233  0.157895  0.631579
234  0.000000  0.421053
235  0.736842  0.947368
236  0.105263  0.684211
237  0.473684  0.789474
238  0.052632  0.315789
239  0.894737  0.842105
240  0.210526  0.157895
241  1.000000  0.894737
242  0.684211  0.263158
243  0.842105  0.368421
244  0.315789  0.000000
245  0.789474  0.736842
246  0.526316  0.105263
247  0.947368  0.578947
248  0.631579  0.473684
249  0.578947  0.736842
250  0.157895  0.526316
251  0.421053  0.894737
252  0.210526  0.631579
253  0.263158  0.789474
254  0.000000  1.000000
255  0.105263  0.368421
256  0.473684  0.947368
257  0.684211  0.315789
258  0.052632  0.842105

[259 rows x 2 columns]
         FTHG      FTAG  HTHG      HTAG        HS        AS       HST  \
0    0.333333  0.500000  0.25  0.333333  0.250000  1.000000  0.133333
1    0.166667  0.333333  0.25  0.333333  0.333333  0.428571  0.333333
2    0.000000  0.166667  0.00  0.000000  0.291667  0.380952  0.200000
3    0.333333  0.000000  0.25  0.000000  0.333333  0.476190  0.266667
4    0.333333  0.333333  0.25  0.000000  0.333333  0.666667  0.400000
5    0.166667  0.000000  0.25  0.000000  0.250000  0.428571  0.333333
6    0.000000  0.166667  0.00  0.000000  0.291667  0.666667  0.333333
7    0.666667  0.000000  0.25  0.000000  0.625000  0.190476  0.666667
8    0.333333  0.000000  0.25  0.000000  0.541667  0.285714  0.600000
9    0.500000  0.333333  0.00  0.333333  0.833333  0.190476  0.866667
10   0.333333  0.333333  0.25  0.000000  0.458333  0.476190  0.466667
11   1.000000  0.166667  0.50  0.000000  0.750000  0.142857  1.000000
12   0.000000  0.000000  0.00  0.000000  0.416667  0.380952  0.466667
13   0.333333  0.166667  0.50  0.000000  0.375000  0.476190  0.266667
14   0.333333  0.333333  0.50  0.000000  0.333333  0.380952  0.400000
15   0.166667  0.000000  0.00  0.000000  0.583333  0.047619  0.333333
16   0.166667  0.000000  0.25  0.000000  0.500000  0.333333  0.333333
17   0.500000  0.500000  0.25  1.000000  0.833333  0.714286  0.733333
18   0.333333  0.166667  0.25  0.000000  0.708333  0.190476  0.600000
19   0.000000  0.500000  0.00  0.000000  0.250000  0.380952  0.066667
20   0.166667  0.333333  0.25  0.333333  0.291667  0.857143  0.466667
21   0.000000  0.166667  0.00  0.333333  0.291667  0.095238  0.333333
22   0.000000  0.000000  0.00  0.000000  0.416667  0.476190  0.333333
23   0.166667  0.000000  0.00  0.000000  0.500000  0.095238  0.266667
24   0.166667  0.000000  0.00  0.000000  0.666667  0.238095  0.533333
25   0.500000  0.000000  0.50  0.000000  0.250000  0.476190  0.266667
26   0.833333  0.500000  1.00  0.333333  0.375000  0.428571  0.533333
27   0.166667  0.000000  0.00  0.000000  0.375000  0.285714  0.466667
28   0.000000  0.833333  0.00  0.333333  0.208333  0.380952  0.133333
29   0.000000  0.166667  0.00  0.000000  0.958333  0.285714  0.733333
..        ...       ...   ...       ...       ...       ...       ...
229  0.166667  0.000000  0.25  0.000000  0.458333  0.380952  0.466667
230  0.500000  0.000000  0.50  0.000000  0.416667  0.238095  0.533333
231  0.166667  0.500000  0.25  0.333333  0.458333  0.190476  0.333333
232  0.333333  0.166667  0.00  0.333333  0.458333  0.190476  0.200000
233  0.500000  0.000000  0.50  0.000000  0.250000  0.142857  0.400000
234  0.333333  0.166667  0.00  0.333333  0.541667  0.190476  0.400000
235  0.333333  0.166667  0.00  0.000000  0.541667  0.190476  0.466667
236  0.000000  0.000000  0.00  0.000000  0.791667  0.190476  0.666667
237  0.166667  0.666667  0.25  0.333333  0.208333  0.619048  0.266667
238  0.166667  0.000000  0.00  0.000000  0.416667  0.523810  0.466667
239  0.333333  0.166667  0.00  0.000000  0.333333  0.571429  0.266667
240  0.500000  0.000000  0.00  0.000000  0.375000  0.095238  0.466667
241  0.333333  0.500000  0.25  0.666667  0.333333  0.238095  0.333333
242  0.333333  0.000000  0.25  0.000000  0.416667  0.333333  0.466667
243  0.000000  0.166667  0.00  0.000000  0.500000  0.142857  0.266667
244  0.000000  0.000000  0.00  0.000000  0.291667  0.190476  0.333333
245  0.500000  0.500000  0.25  0.666667  0.375000  0.238095  0.133333
246  0.000000  0.666667  0.00  0.666667  0.291667  0.571429  0.133333
247  0.166667  0.000000  0.00  0.000000  0.333333  0.285714  0.400000
248  0.166667  0.166667  0.25  0.000000  0.208333  0.142857  0.133333
249  0.333333  0.166667  0.50  0.333333  0.458333  0.809524  0.333333
250  0.500000  0.500000  0.25  0.666667  0.500000  0.238095  0.600000
251  0.500000  0.000000  0.25  0.000000  0.208333  0.238095  0.266667
252  0.166667  0.000000  0.25  0.000000  0.250000  0.428571  0.266667
253  0.500000  0.166667  0.50  0.333333  0.666667  0.238095  0.666667
254  0.000000  0.000000  0.00  0.000000  0.375000  0.047619  0.400000
255  0.166667  0.333333  0.00  0.666667  0.500000  0.095238  0.333333
256  0.166667  0.333333  0.00  0.666667  0.291667  0.571429  0.133333
257  0.500000  0.000000  0.00  0.000000  0.333333  0.333333  0.400000
258  0.333333  0.166667  0.25  0.333333  0.416667  0.428571  0.400000

          AST    HF        AF    HC        AC        HY        AY   HR   AR
0    0.846154  0.15  0.217391  0.00  0.615385  0.333333  0.000000  0.0  0.0
1    0.461538  0.20  0.043478  0.20  0.538462  0.000000  0.000000  0.0  0.0
2    0.384615  0.60  0.304348  0.35  0.000000  0.666667  0.285714  0.5  0.0
3    0.384615  0.75  0.652174  0.30  0.461538  0.500000  0.428571  0.0  0.0
4    0.461538  0.30  0.391304  0.20  0.384615  0.333333  0.285714  0.0  0.0
5    0.307692  0.95  0.304348  0.20  0.307692  0.500000  0.285714  0.0  0.0
6    1.000000  0.30  0.434783  0.30  0.384615  0.166667  0.428571  0.0  0.0
7    0.076923  0.50  0.260870  0.20  0.307692  0.000000  0.285714  0.0  0.0
8    0.230769  0.40  0.391304  0.30  0.153846  0.500000  0.285714  0.0  0.0
9    0.307692  0.40  0.217391  0.25  0.076923  0.333333  0.285714  0.0  0.0
10   0.461538  0.50  0.434783  0.35  0.153846  0.666667  0.571429  0.0  0.5
11   0.230769  0.50  0.173913  0.10  0.230769  0.166667  0.428571  0.0  0.0
12   0.384615  0.55  0.347826  0.10  0.384615  0.333333  0.142857  0.0  0.0
13   0.615385  0.50  0.478261  0.15  0.461538  0.500000  0.285714  0.0  0.0
14   0.538462  0.60  0.347826  0.25  0.307692  0.166667  0.285714  0.0  0.0
15   0.000000  0.45  0.434783  0.35  0.153846  0.833333  0.285714  0.0  0.0
16   0.307692  0.10  0.260870  0.40  0.538462  0.166667  0.428571  0.0  0.0
17   0.769231  0.25  0.391304  0.15  0.846154  0.166667  0.142857  0.0  0.0
18   0.230769  0.20  0.086957  0.40  0.230769  0.000000  0.285714  0.0  0.0
19   0.307692  0.15  0.260870  0.15  0.538462  0.166667  0.142857  0.0  0.0
20   0.769231  0.55  0.217391  0.20  0.538462  0.166667  0.428571  0.0  0.0
21   0.230769  0.60  0.695652  0.25  0.307692  0.333333  0.285714  0.0  0.0
22   0.307692  0.30  0.304348  0.20  0.461538  0.166667  0.142857  0.0  0.0
23   0.076923  0.30  0.478261  0.55  0.307692  0.500000  0.142857  0.0  0.0
24   0.384615  0.35  0.173913  0.35  0.538462  0.166667  0.285714  0.0  0.0
25   0.461538  0.45  0.652174  0.20  0.384615  0.333333  0.571429  0.0  0.0
26   0.615385  0.40  0.695652  0.10  0.769231  0.500000  0.428571  0.0  0.0
27   0.230769  0.60  0.521739  0.45  0.769231  0.166667  0.285714  0.0  0.0
28   0.538462  0.40  0.478261  0.25  0.230769  0.500000  0.142857  0.0  0.0
29   0.461538  0.30  0.173913  0.50  0.076923  0.333333  0.285714  0.0  0.0
..        ...   ...       ...   ...       ...       ...       ...  ...  ...
229  0.461538  0.85  0.739130  0.45  0.153846  0.333333  0.571429  0.0  0.5
230  0.076923  0.45  0.652174  0.25  0.538462  0.333333  0.428571  0.0  0.0
231  0.230769  0.30  0.217391  0.25  0.153846  0.166667  0.285714  0.0  0.0
232  0.230769  0.85  0.304348  0.05  0.307692  0.833333  0.142857  0.5  0.0
233  0.153846  0.35  0.260870  0.15  0.230769  0.166667  0.428571  0.0  0.0
234  0.461538  0.40  0.347826  0.35  0.230769  0.500000  0.285714  0.0  0.0
235  0.153846  0.30  0.304348  0.45  0.384615  0.500000  0.142857  0.0  0.0
236  0.076923  0.70  0.391304  0.75  0.307692  0.833333  0.428571  0.0  0.0
237  0.692308  0.50  0.434783  0.15  0.769231  0.500000  0.571429  0.0  0.0
238  0.692308  0.35  0.739130  0.30  0.307692  0.833333  0.571429  0.0  0.0
239  0.769231  0.55  0.478261  0.45  0.538462  0.500000  0.571429  0.0  0.0
240  0.076923  0.45  0.217391  0.30  0.153846  0.166667  0.142857  0.0  0.0
241  0.384615  0.70  0.304348  0.20  0.615385  0.333333  0.285714  0.0  0.0
242  0.307692  0.65  0.608696  0.20  0.307692  0.333333  0.142857  0.0  0.0
243  0.307692  0.40  0.565217  0.20  0.384615  0.333333  0.285714  0.0  0.0
244  0.153846  0.80  0.782609  0.20  0.461538  0.333333  0.428571  0.0  0.0
245  0.461538  0.45  0.478261  0.45  0.461538  0.333333  0.571429  0.0  0.0
246  0.384615  0.45  0.130435  0.25  0.153846  0.333333  0.142857  0.0  0.0
247  0.076923  0.25  0.565217  0.15  0.384615  0.166667  0.285714  0.0  0.0
248  0.230769  0.70  0.434783  0.15  0.384615  0.666667  0.142857  0.5  0.0
249  0.538462  0.40  0.173913  0.05  0.384615  0.833333  0.428571  0.0  0.0
250  0.538462  0.30  0.565217  0.40  0.153846  0.166667  0.428571  0.0  0.0
251  0.230769  0.45  0.478261  0.25  0.538462  0.666667  0.714286  0.0  0.5
252  0.461538  0.80  0.217391  0.30  0.461538  0.500000  0.000000  0.0  0.5
253  0.307692  0.25  0.521739  0.40  0.384615  0.666667  0.285714  0.0  0.0
254  0.000000  0.55  0.521739  0.40  0.153846  0.333333  0.571429  0.0  0.5
255  0.230769  0.30  0.434783  0.60  0.307692  0.500000  0.857143  0.5  0.5
256  0.769231  0.30  0.434783  0.25  0.307692  0.333333  0.428571  0.5  0.0
257  0.384615  0.30  0.608696  0.35  0.307692  0.166667  0.571429  0.0  0.0
258  0.692308  0.85  0.695652  0.30  0.461538  0.500000  0.428571  0.0  0.0

[259 rows x 16 columns]
<class 'pandas.core.frame.DataFrame'>

In [119]:
lr = LinearRegression()
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:2], df.iloc[:,2:18], test_size=0.2, shuffle=False)

In [120]:
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [121]:
pred = lr.predict(x_test)

In [122]:
print(pred)

[[ 1.49970325  1.22254316  0.6797705   0.466393   11.36428768  9.77698499
   5.80536028  4.94427339 12.51929814 12.97892451  5.64249537  4.98929895
   2.14259164  2.53426748  0.08680639  0.12581026]
 [ 1.44211705  1.22618624  0.61760139  0.48135708 11.06862026  9.51797617
   5.62523416  4.8393575  12.9586063  13.84171352  5.6772446   4.74254279
   2.16048235  2.58576906  0.09404499  0.08488555]
 [ 1.59171822  1.19422908  0.79280512  0.43264077 11.99595209 10.17461301
   6.1482875   5.11054575 11.62058577 11.21567414  5.68237163  5.49282411
   2.10315022  2.46109397  0.07934178  0.20764735]
 [ 1.4964243   1.14964855  0.7207452   0.43525965 11.86494308  9.70947977
   5.97421163  4.93385012 11.90485077 11.77800314  5.95452667  5.33028586
   2.10833325  2.56683689  0.10054908  0.17692608]
 [ 1.46199555  1.17431956  0.66987969  0.4540478  11.52894608  9.57086057
   5.81141053  4.87249365 12.36425498 12.67846449  5.87990118  5.07351686
   2.12988396  2.58850882  0.10077508  0.1360137 ]
 [ 1.29856135  1.04688966  0.57733175  0.43623684 11.66508946  8.73634589
   5.63774753  4.56634869 12.4059072  12.77126728  6.56285228  5.04231188
   2.11417547  2.79052859  0.14644173  0.12059143]
 [ 1.379305    1.06427451  0.65080446  0.42509684 11.9204273   9.11574432
   5.83519866  4.71482401 11.9866951  11.94615061  6.41872833  5.27905522
   2.09994476  2.70919734  0.13219052  0.16152847]
 [ 1.41762754  1.2249239   0.59287503  0.4864906  10.96278617  9.40579916
   5.55552124  4.79456911 13.12083486 14.16055035  5.7039474   4.65126083
   2.16673386  2.60881087  0.09763604  0.06953725]
 [ 1.63004076  1.35487847  0.73487569  0.49403452 11.03831096 10.46466785
   5.86861009  5.19029085 12.75472553 13.43007389  4.9675907   4.86502972
   2.16993932  2.36070749  0.04478729  0.11565614]
 [ 1.42889885  1.17922497  0.63243695  0.46387836 11.33911275  9.42402876
   5.70099733  4.81236615 12.64133459 13.22241666  5.88794761  4.91804265
   2.14152315  2.6169686   0.10442263  0.1104373 ]
 [ 1.33893318  1.05558208  0.61406811  0.43066684 11.79275838  8.92604511
   5.73647309  4.64058635 12.19630115 12.35870895  6.49079031  5.16068355
   2.10706012  2.74986296  0.13931613  0.14105995]
 [ 1.57050766  1.26586135  0.72710406  0.46890764 11.38946261 10.12994122
   5.90972323  5.07618064 12.3972617  12.73543235  5.39704314  5.06055525
   2.14366013  2.45156635  0.06919014  0.14118323]
 [ 1.58106174  1.3523538   0.68542296  0.50430156 10.82664279 10.24031383
   5.72918425  5.10071408 13.07918264 14.06774756  5.0209963   4.68246581
   2.18244235  2.4067911   0.0519694   0.08495952]
 [ 1.58044691  1.23992801  0.75324321  0.45525301 11.61962552 10.15638341
   6.00281141  5.09274872 12.10008604 12.15380784  5.49837143  5.22604229
   2.12836093  2.45293623  0.07255519  0.1667473 ]
 [ 1.34354419  1.1087111   0.58651618  0.4528426  11.43826665  8.98533772
   5.62000965  4.65223859 12.62842392 13.20312114  6.26143093  4.92099143
   2.13140699  2.72408141  0.12899498  0.10528011]
 [ 1.64725513  1.34254297  0.76030845  0.48464044 11.20630946 10.53397745
   5.95001064  5.22096908 12.52502342 12.97984321  5.00490344  4.99341422
   2.15916397  2.34987153  0.04467429  0.13611233]
 [ 1.42029166  1.18539272  0.61972057  0.4685754  11.2551135   9.38937395
   5.66029706  4.79702703 12.75618564 13.447532    5.86929124  4.8538504
   2.14691083  2.62238658  0.10447914  0.10020921]
 [ 1.46332761  1.15455397  0.68330246  0.4450902  11.67510974  9.56264796
   5.86379844  4.87372261 12.18193037 12.32195531  5.96257309  5.17481165
   2.11997244  2.59529668  0.10419663  0.15134968]
 [ 1.6862949   1.37100099  0.78362203  0.48802805 11.18781472 10.73188927
   5.9963483   5.29397779 12.49774198 12.92379405  4.85016955  5.0104911
   2.16196013  2.30241805  0.03412714  0.14124487]
 [ 1.42428784  1.12609595  0.65998888  0.4417026  11.69360449  9.36473615
   5.81746078  4.80071391 12.20921182 12.37800447  6.11730698  5.15773477
   2.11717628  2.64275016  0.11474378  0.14621714]
 [ 1.3990811   1.25702499  0.5540195   0.50484228 10.64862401  9.34470216
   5.42173279  4.76266192 13.53286157 14.9672902   5.58396274  4.42158154
   2.18742074  2.61285897  0.09432749  0.03374508]
 [ 1.54601815  1.26459901  0.70237769  0.47404116 11.28362852 10.01776421
   5.84001031  5.03139225 12.55949026 13.05426919  5.42374594  4.96927329
   2.14991164  2.47460816  0.07278119  0.12583492]
 [ 1.64858719  1.32277738  0.77373122  0.47568285 11.35247312 10.52576485
   6.00239854  5.22219804 12.34269882 12.62333403  5.08757536  5.09470901
   2.14925245  2.35665939  0.04809584  0.1514483 ]
 [ 1.31905468  1.10744876  0.56178981  0.45797612 11.33243256  8.87316071
   5.55029673  4.6074502  12.79065247 13.52195797  6.28813373  4.82970948
   2.13765851  2.74712321  0.13258603  0.0899318 ]
 [ 1.5427392   1.19170441  0.74335239  0.44290781 11.78428392  9.95025899
   6.00886166  5.02096897 11.94504288 11.85334782  5.73577723  5.3102602
   2.11565325  2.50717757  0.08652388  0.17695074]
 [ 1.49109607  1.22871091  0.66705412  0.47109004 11.28028843  9.74233018
   5.76466001  4.92893428 12.6341492  13.20403984  5.623839    4.9251067
   2.14797932  2.53968546  0.08686289  0.11558217]
 [ 1.40113039  1.10506802  0.64868528  0.43787852 11.73393406  9.24434653
   5.80013576  4.75715448 12.18911576 12.34033213  6.2266817   5.1677476
   2.11351628  2.67257982  0.12175638  0.14620482]
 [ 1.44283428  1.09399486  0.69884441  0.42335093 12.00776665  9.42583315
   5.95124923  4.8326211  11.7971851  11.57126462  6.23729164  5.38741406
   2.09648941  2.63870206  0.11805233  0.18200931]
 [ 1.3858629   1.21006372  0.56885506  0.48736356 10.9191165   9.25075475
   5.49749596  4.73567057 13.21558985 14.34799335  5.79466575  4.59708141
   2.16846154  2.64405851  0.10470514  0.05929682]
 [ 1.37797294  1.0840401   0.63738169  0.43405444 11.77426364  9.12395692
   5.78281075  4.71359505 12.1690197  12.30265979  6.33605642  5.17776043
   2.10985628  2.70240948  0.12876898  0.14619249]
 [ 1.39713421  1.16436479  0.60841697  0.46475132 11.29544308  9.26898434
   5.64297204  4.7534676  12.73608958 13.40985966  5.97866595  4.86386323
   2.14325083  2.65221624  0.11149173  0.10019688]
 [ 1.48187404  1.12245287  0.72215799  0.42673853 11.9892719   9.62374496
   5.99758689  4.9056298  11.76990366 11.51521546  6.08255775  5.40449094
   2.09928557  2.59124857  0.10750518  0.18714185]
 [ 1.43945293  1.26571742  0.59075585  0.49927228 10.77629293  9.53440137
   5.52045835  4.83689958 13.32325552 14.55473187  5.51190077  4.53995321
   2.18030538  2.57219335  0.08720189  0.0542136 ]
 [ 1.55134639  1.18553666  0.75606877  0.43821077 11.86828317  9.9849138
   6.04956193  5.03630809 11.83019182 11.62823248  5.7544336   5.37445245
   2.11026558  2.50175959  0.08646738  0.18717884]
 [ 1.43812087  1.28548301  0.57733308  0.50822988 10.63012927  9.54261398
   5.46807045  4.83567062 13.50558013 14.91124105  5.42922885  4.43865842
   2.1902169   2.56540549  0.08378035  0.03887762]
 [ 1.58505792  1.29305703  0.72569127  0.47742876 11.26513378 10.21567602
   5.88634797  5.10440095 12.53220881 12.99822003  5.26901205  4.98635017
   2.1527078   2.42715467  0.06223404  0.13096746]
 [ 1.57511867  1.31899037  0.69955213  0.4910834  11.03497087 10.18923383
   5.79325978  5.08783288 12.82938447 13.57984454  5.16768376  4.82086313
   2.168007    2.4257848   0.05886899  0.10540338]
 [ 1.6135436   1.2350226   0.79068595  0.44542245 11.80945885 10.30321522
   6.11322461  5.15287622 11.82300644 11.60985566  5.490325    5.38151649
   2.11672174  2.42447645  0.06890763  0.1923237 ]
 [ 1.45666731  1.25338191  0.61618861  0.4898782  10.94429143  9.60371098
   5.6018589   4.86757781 13.09355341 14.10450119  5.54921351  4.66833771
   2.16953003  2.56135738  0.08708889  0.07466979]
 [ 1.61087949  1.27455378  0.76384041  0.46333765 11.51713153 10.31964043
   6.00844879  5.1504183  12.18765565 12.32287402  5.32498116  5.17892692
   2.13654477  2.41090073  0.06206454  0.16165174]
 [ 1.52613965  1.3164657   0.6500994   0.50135044 10.8233027   9.96487981
   5.65383394  4.9982561  13.15384158 14.21751822  5.22108936  4.63829922
   2.18051003  2.4718684   0.06605109  0.07470677]
 [ 1.51425351  1.24973884  0.67835772  0.47491412 11.23995885  9.86271979
   5.78198502  4.97249371 12.65424525 13.24171218  5.51446428  4.91509387
   2.15163932  2.5098558   0.07985029  0.1155945 ]
 [ 1.42756679  1.19899056  0.61901418  0.47283596 11.19294909  9.43224136
   5.64860943  4.81113719 12.82365919 13.57892584  5.80527569  4.81674786
   2.15143467  2.61018074  0.10100109  0.09510132]
 [ 1.43289503  1.1199282   0.67270526  0.43700556 11.77760373  9.39939095
   5.85816105  4.81605303 12.09436076 12.15288913  6.13596336  5.22192702
   2.1117886   2.63733218  0.11468728  0.15644524]
 [ 1.35809445  1.13590678  0.58510339  0.46136372 11.31393782  9.07107253
   5.59663439  4.6804589  12.76337103 13.46590882  6.13339984  4.84678636
   2.14045467  2.69966973  0.12203888  0.09506434]
 [ 1.40840552  1.11866586  0.64797889  0.44213908 11.67176965  9.28721394
   5.78844813  4.77126464 12.25658931 12.47172597  6.16266616  5.13064506
   2.11804012  2.66037398  0.11827833  0.14109693]
 [ 1.36803369  1.10997344  0.61124254  0.44770908 11.54410073  9.09751472
   5.68972257  4.69702698 12.46619537 12.8842843   6.23472813  5.01227339
   2.12515547  2.7010396   0.12540393  0.12062841]
 [ 1.26812877  1.01226389  0.56673455  0.4281522  11.76758345  8.57308888
   5.63211014  4.5086791  12.31833759 12.6022011   6.73624254  5.08942725
   2.10599163  2.83256409  0.15693237  0.12568699]
 [ 1.47326685  1.12862063  0.70944161  0.43143557 11.90527265  9.58909016
   5.95688662  4.89029069 11.88475471 11.7403308   6.06390138  5.34029869
   2.10467325  2.59666655  0.10756168  0.17691376]
 [ 1.34948726  1.14207453  0.57238701  0.46606076 11.22993857  9.03641772
   5.55593411  4.66511978 12.87822208 13.69102415  6.11474347  4.78259411
   2.14584235  2.70508771  0.12209538  0.08483624]
 [ 1.5691756   1.28562694  0.71368129  0.47786524 11.24329894 10.13815382
   5.85733532  5.07495168 12.57958631 13.09194153  5.31437122  4.95926046
   2.15357164  2.44477849  0.06576859  0.12584725]
 [ 1.32305086  1.04815199  0.60205812  0.43110332 11.77092355  8.8485229
   5.70746045  4.61113708 12.24367865 12.45243044  6.53614948  5.13359384
   2.10792396  2.76748678  0.14285068  0.13593974]]

In [137]:
for i in range(len(y_test.values.T)): #verifico l'accuratezza di ogni variabile predetta per tutti i casi di test
    print(r2_score(y_true=y_test.values[:,i], y_pred=pred[:,i]))

-0.06433957170865057
0.0016739409049633114
-0.06544238460254248
-0.0440792235349301
-0.06571580751603823
-0.08571971046619109
-0.02114320290620908
-0.018374636312701087
-0.031126460283667612
-0.021047174012766012
-0.011678783291133144
-0.08758854517982306
0.0017301740362112294
0.006010411113237857
-0.009676734707195322
-0.012399756800896888

In [124]:
print(pred[:,10])
y_test.values[:,10]

[5.64249537 5.6772446  5.68237163 5.95452667 5.87990118 6.56285228
 6.41872833 5.7039474  4.9675907  5.88794761 6.49079031 5.39704314
 5.0209963  5.49837143 6.26143093 5.00490344 5.86929124 5.96257309
 4.85016955 6.11730698 5.58396274 5.42374594 5.08757536 6.28813373
 5.73577723 5.623839   6.2266817  6.23729164 5.79466575 6.33605642
 5.97866595 6.08255775 5.51190077 5.7544336  5.42922885 5.26901205
 5.16768376 5.490325   5.54921351 5.32498116 5.22108936 5.51446428
 5.80527569 6.13596336 6.13339984 6.16266616 6.23472813 6.73624254
 6.06390138 6.11474347 5.31437122 6.53614948]

array([ 1,  6,  1, 10, 12,  5,  4,  6, 10, 11,  1,  2,  2,  3,  7,  5,  2,
        9, 13,  2,  9,  8,  9,  5,  5,  1,  3,  7,  9, 15,  3,  6,  9,  6,
        4,  4,  4,  4,  9,  5,  3,  3,  1,  8,  5,  6,  8,  8, 12,  5,  7,
        6], dtype=int64)

In [125]:
x_test.values.shape
pred.shape

(52, 16)

In [126]:
final_array = np.concatenate((x_test.values, pred), axis = 1)

In [127]:
df_final = pd.DataFrame(final_array)

In [128]:
df_final.columns = df.columns

In [129]:
final_array_true = np.concatenate((x_test.values, y_test.values), axis = 1)

In [130]:
df_final_true = pd.DataFrame(final_array_true)

In [131]:
df_final_true.columns = df.columns

In [141]:
nomi_squadre = dict((v,k) for k,v in squadre.items())
df_final['HomeTeam'] = df_final['HomeTeam'].map(nomi_squadre)
df_final['AwayTeam'] = df_final['AwayTeam'].map(nomi_squadre)
df_final_true['HomeTeam'] = df_final_true['HomeTeam'].map(nomi_squadre)
df_final_true['AwayTeam'] = df_final_true['AwayTeam'].map(nomi_squadre)

In [142]:
df_final_true.head()

,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,Parma,Spal,2,3,1,0,9,15,5,6,9,13,1,10,2,4,0,0
1,Torino,Inter,1,0,1,0,7,9,4,4,19,12,6,7,3,3,0,1
2,Empoli,Genoa,1,3,0,1,13,12,7,7,8,7,1,3,1,2,0,0
3,Empoli,Chievo,2,2,1,2,11,10,9,4,9,12,10,6,0,2,0,0
4,Juventus,Parma,3,3,1,0,18,11,9,5,6,11,12,4,1,2,0,0

In [143]:
df_final.head()

,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,Parma,Spal,1.499703,1.222543,0.679771,0.466393,11.364288,9.776985,5.805360,4.944273,12.519298,12.978925,5.642495,4.989299,2.142592,2.534267,0.086806,0.125810
1,Torino,Inter,1.442117,1.226186,0.617601,0.481357,11.068620,9.517976,5.625234,4.839358,12.958606,13.841714,5.677245,4.742543,2.160482,2.585769,0.094045,0.084886
2,Empoli,Genoa,1.591718,1.194229,0.792805,0.432641,11.995952,10.174613,6.148287,5.110546,11.620586,11.215674,5.682372,5.492824,2.103150,2.461094,0.079342,0.207647
3,Empoli,Chievo,1.496424,1.149649,0.720745,0.435260,11.864943,9.709480,5.974212,4.933850,11.904851,11.778003,5.954527,5.330286,2.108333,2.566837,0.100549,0.176926
4,Juventus,Parma,1.461996,1.174320,0.669880,0.454048,11.528946,9.570861,5.811411,4.872494,12.364255,12.678464,5.879901,5.073517,2.129884,2.588509,0.100775,0.136014

In [144]:
lr.intercept_

array([ 1.56989283,  1.15343556,  0.7949243 ,  0.41985909, 12.18244533,
       10.0460108 ,  6.18335039,  5.06821528, 11.41816511, 10.82149263,
        5.87441826,  5.60413173,  2.0895787 ,  2.49771149,  0.08977593,
        0.222971  ])

In [145]:
lr.coef_

array([[ 0.00727513, -0.01588232],
       [ 0.01359784, -0.00743009],
       [-0.00070639, -0.01200999],
       [ 0.00426056,  0.00043648],
       [-0.06216441, -0.02183484],
       [ 0.0428674 , -0.07752221],
       [-0.01168763, -0.02901264],
       [ 0.01411016, -0.02944927],
       [ 0.06747355,  0.0473775 ],
       [ 0.13139384,  0.0937215 ],
       [-0.06401554,  0.04535917],
       [-0.03710254, -0.02708971],
       [ 0.00452384,  0.00086384],
       [-0.01220584,  0.01762382],
       [-0.00347805,  0.00353455],
       [-0.00510788, -0.00512021]])